In [5]:
import pandas as pd

# 读取数据
df = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])

# 数据处理
df['销售金额'] = df['销售数量'] * df['单价']
df

# 写入数据
df.to_csv('data/sales_result.csv',index=False)

In [10]:
# 数据查看 -- head tail describe info shape cloumns
df1 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])
df1.head(10) # 查看前10行
df1.tail(10) # 查看后10行
df1.describe() # 描述性统计
df1.info() # 数据信息
df1.shape # 数据维度
df1.columns # 列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [18]:
# 数据选择
df2 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'],index_col='订单号')
# 选择列
# 单列
df2['产品类别']

# 多列
df2[['产品类别','产品名称']]

# 选择行 iloc loc
# iloc 是根据行号来选择的（不包含结束位置）,语法:df.iloc[开始行号:结束行号,开始列号:结束列号]
df2.iloc[0:5:1]
df2.iloc[0:5]

# loc 是根据索引标签来选择的（包含结束位置）,语法:df.loc[开始行标签:结束行标签,开始列标签:结束列标签]
df2.loc[6805677496:6801664364:1]

            产品类别  产品名称  销售数量   单价
订单号
6805677496  家居用品    枕头    10  199
5857234132    食品    海苔     5   29
5888085059  电子产品  智能音箱     5  399
6823473137    食品    面包     3   29
6801664364    食品    薯片     2   19

In [25]:
df3 = pd.read_csv('data/sales.csv')
# 1.获取销售数量>=10的订单数据
df3[df3['销售数量']>=10]

# 2.获取产品类别为食品或者图书的订单数据
df3[df3['产品类别'].isin(['食品','图书'])]

# 3.获取单价在100-200之间的订单数据 -> 范围between -》默认包含边界(inclusive = "left")
df3[df3['单价'].between(100,200)]

# 4.获取销售数量>=8,并且单价>=100的订单数据
df3[(df3['销售数量']>=8) & (df3['单价']>=100)]

# 5.获取产品类别为食品或者服装，支付方式为微信或者支付宝
df3[(df3['产品类别'].isin(['食品','服装'])) & (df3['支付方式'].isin(['微信','支付宝']))]

            订单号 产品类别 产品名称  销售数量   单价 客户所在城市 支付方式        订单日期
10   5808071569   食品  矿泉水     9   29     重庆  支付宝  2025-06-04
26   5854211330   食品   果干     9   59     长沙  支付宝  2025-06-07
31   5837205437   服装   短裤     2  149     昆明  支付宝  2025-06-08
32   6816687256   服装  运动裤     7  249     杭州  支付宝  2025-06-09
43   6896687125   食品   果汁     2   39     合肥  支付宝  2025-06-12
..          ...  ...  ...   ...  ...    ...  ...         ...
983  6890836887   服装   短裤     8  149     杭州  支付宝  2026-03-15
988  6845708709   服装   衬衫     7  299     苏州  支付宝  2026-03-16
996  5808511756   食品   坚果     2   79     成都  支付宝  2026-03-20
997  5811169466   服装   围巾     4  129     南京  支付宝  2026-03-20
998  6876456690   食品   果汁     7   39     广州  支付宝  2026-03-20

[183 rows x 8 columns]