In [7]:
import pandas as pd

df = pd.read_csv('data/sales.csv')
df.head(10)
# 查看缺失值
df.isnull()

# 删除缺失值
df.dropna() #删除缺失值所在行
# 删除缺失值所在列
df.dropna(axis=1)

# 填充缺失值
df.fillna("---")
df.ffill() #填充缺失值，填充上一行数据
df.bfill() #填充缺失值，填充下一行数据

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19     广州  微信支付  2025/06/02
..          ...   ...   ...   ...  ...    ...   ...         ...
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]

In [12]:
# 处理重复值
# 查看重复值
df.duplicated() # 查看重复值(所有列的数据都重复)

df.duplicated(subset=['订单号']) # 查看重复值(指定列的数据重复)

# 删除重复值
df.drop_duplicates(subset=['订单号']) #kepp = 'first' 保留第一行的重复值 keep = 'last' 保留最后一行重复值 keep = False 删除所有重复值

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [14]:
# 异常值处理
# 查看异常值
df[df['单价'] < 0]

# 删除异常值
df.drop(df[df['单价'] < 0].index)

# 修复异常值
df['单价'] = df['单价'].abs() #绝对值
df

          订单号 产品类别 产品名称  销售数量  单价 客户所在城市 支付方式        订单日期
6  6857752388   服装   袜子     7 -29     郑州   现金  2025-06-02

In [1]:
# 数据格式处理
df['订单日期'] = df['订单日期'].str.replace('/', '-')
df

NameError: name 'df' is not defined